[package]
name = "sparky"
version = "1.0.0"
authors = ["Paul Blouët <paul@paulblouet.fr>"]
edition = "2018"

[features]
default = ["exylobby"]
exylobby = []
ytp = []

[dependencies]
base64 = "0.11.0"
bincode = "1.2.1"
chrono = "0.4.10"
dotenv = "0.15.0"
flate2 = "1.0.13"
Inflector = "0.11.4"
serde = "1.0.104"
serenity = "0.8.0"
