[package]
name = "sparky"
version = "1.4.3"
authors = ["Paul Blouët <paul@paulblouet.fr>"]
edition = "2018"

[features]
default = ["exylobby"]
exylobby = []
ytp = []

[dependencies]
Inflector = "0.11.4"
anyhow = "1.0.26"
base64 = "0.12.0"
bincode = "1.2.1"
boolinator = "2.4.0"
chrono = "0.4.10"
ctrlc = { version = "3.1.4", features = ["termination"] }
dotenv = "0.15.0"
env_logger = "0.7.1"
flate2 = "1.0.13"
lazy_static = "1.4.0"
log = "0.4.8"
serde = "1.0.104"
serenity = "0.8.0"
