[package]
name = "sparky"
version = "2.6.1"
authors = ["Paul Blouët <paul@paulblouet.fr>"]
edition = "2018"
[dependencies.Inflector]
version = "0.11.4"

[dependencies.anyhow]
version = "1.0.26"

[dependencies.base64]
version = "0.12.0"

[dependencies.bincode]
version = "1.2.1"

[dependencies.boolinator]
version = "2.4.0"

[dependencies.chrono]
version = "0.4.10"

[dependencies.chrono-tz]
version = "0.5.1"

[dependencies.clap]
version = "2.33.0"

[dependencies.ctrlc]
version = "3.1.4"
features = ["termination"]

[dependencies.dotenv]
version = "0.15.0"

[dependencies.env_logger]
version = "0.7.1"

[dependencies.flate2]
version = "1.0.13"

[dependencies.log]
version = "0.4.8"

[dependencies.nom]
version = "5.1.1"

[dependencies.rand]
version = "0.7.3"

[dependencies.serde]
version = "1.0.104"

[dependencies.serenity]
version = "0.8.0"

[dependencies.typemap]
version = "0.3.3"

[features]
default = ["exylobby"]
exylobby = []
ytp = []
