[package]
name = "sparky_macros"
version = "1.0.0"
authors = ["Paul Blouët <paul.blouet@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
quote = "1.0.7"
syn = { version = "1.0.39", features = ["full"] }
