name: Continuous Deployment

on:
  push:
    tags:
      - v*

env:
  REGION: us-east1-b
  HOST: base-micro-2

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            # Changes
            * First change

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: base-micro-admin@durlendiamenfes1.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCLOUD_CD }}
      - run: gcloud config set project durlendiamenfes1
      - run: gcloud compute ssh $HOST --command='sudo systemctl stop sparky' --zone $REGION
      - run: gcloud compute scp $GITHUB_WORKSPACE/target/release/sparky $HOST:/opt/sparky/ --zone $REGION
      - run: gcloud compute ssh $HOST --command='sudo systemctl start sparky' --zone $REGION
